# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06a79f1d44e2206e3054a18b086be48df645b0ccb0edf694667ce12a885f24bbdbd3a3bd855044815d6dabdd7d526fdbd264144e2798cea711ea96bdaf3ef1bb

test:
  secret_key_base: 7803891b1a999ec83be09d3373d45f9c90f98ab4362674ac5bdc78dda900d150cea99a3ee017ef36b02e2fec41028eb0e23f388bc7768e70c0e5532566a0f510

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
